DO NOT MERGE make system health check failures more readable
Turned it into a parameterized test against an array of
dropbox labels to check, sample error message:
There was 1 failure:
1)
checkCrash[system_app_crash](com.android.devicehealth.tests.BasicHealthCheck)
java.lang.AssertionError: expected:<0> but was:<9>
...

Bug: 35182949
Test: build test apk, run against know bad build
Change-Id: I82789e98468cb1733a7a057044e5c408e1b3f55a
(cherry picked from commit ae34118eb81562821052c3d15d62f48a3bf82255)