Basic health check test apk
Check for app crashes by looking in the dropbox folder.

Tests:

"am instrument -w -r -e class com.android.devicehealth.tests.BasicHealthCheck
com.android.devicehealth.tests/android.support.test.runner.AndroidJUnitRunner"

Good build(ORF74B): Test successfully passed

Bad build(3557851) with systemui crash:
java.lang.AssertionError: system_app_crash count = 972, system_app_native_crash count = 0,
                          system_server_anr count = 0

Bug: 32978343
Change-Id: I9421d983e057eb8d0fdd343746959a70a7ed5648
(cherry picked from commit 52c0350116e06e698292600e673b98f3ccddac5c)